### PR TITLE
[README] Add contribution guide reference to README #293

### PR DESCRIPTION
**Pull request by safimuhammad**
…enchmark/user-guide/contributing-workloads/#testing-the-workload added to the readme.

### Description
Tried resolving issue #293 by adding an official contribution guide directly in the main Readme.

### Issues Resolved
Now contributors can directly refer to the main Readme for official contribution guidelines instead of an external link.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cgchinmay** [comment]
@safimuhammad Thanks for the PR. you need to sign your commit for DCO check to pass.

**Comment by safimuhammad** [comment]
I have signed the commits the DCO is still failing.

**Comment by safimuhammad** [comment]
@cgchinmay  the commit messages include the sign-off and yet it still declines, is there anything I am missing?

**Comment by cgchinmay** [comment]
> @cgchinmay the commit messages include the sign-off and yet it still declines, is there anything I am missing?

you may need to amend your previous commit with sign-off.

**Comment by safimuhammad** [comment]
Thanks, fixed it.

**Review by IanHoang — CHANGES_REQUESTED** [review]
Left one comment

**Comment by safimuhammad** [comment]
Thanks @IanHoang  said changes are done please have a look.

**Review by IanHoang — APPROVED** [review]
LGTM

**Pull request merged**
